dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get -y install ffmpeg libavcodec-extra
install:
  - pip install -r requirements.txt -r requirements-dev.txt
before_script:
  - python3 setup.py develop
script:
  - ./setup_venv.sh && . venv/bin/activate && ./pytest.sh
after_success:
  - coveralls
