dist: xenial
language: python
python:
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get -y install ffmpeg libavcodec-extra
install:
  - pip install -r requirements.txt -r requirements-dev.txt
before_script:
  - python3 setup.py develop
script:
  - ./pytest.sh | tee pytest.log
after_success:
  - coveralls
  - CODECOV_TOKEN="739130b8-72eb-4a55-9ee7-12713c9df60d" bash <(curl -s https://codecov.io/bash)
