dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt -r requirements-dev.txt
before_script:
  - python3 setup.py develop
script:
  - ./pytest.sh
after_success:
  - coveralls
